/*VERIFICAR OS BANCOS DE DADOS*/
SHOW DATABASES;

/*UTILIZAR O BANCO FUNCIONÁRIOS*/
USE FUNCIONÁRIOS;

/*VERIFICAR AS TABELAS*/
SHOW TABLES;

/*DESCRIÇÃO DA TABELAS DE FUNCIONÁRIOS*/
DESC FUNCIONARIOS;

/*EXERCÍCIO 1: TRAGA OS FUNCIONÁRIOS QUE TRABALHAM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO DE ROUPAS*/

/*APRESENTAR TODOS OS NOMES DOS FUNCIONÁRIOS DOS DEPARTAMENTOS DE FILMES E DE ROUPAS POR ORDEM DE ID*/
SELECT idFuncionario, nome, departamento FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'FILMES' OR DEPARTAMENTO = 'ROUPAS';

/*APRESENTAR A QUANTIDADE DE FUNCIONÁRIOSDOS DEPARTAMENTOS DE FILMES E DE ROUPAS*/
SELECT idFuncionario, nome, departamento, COUNT(*)
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='ROUPAS')
GROUP BY DEPARTAMENTO;

/*APRESENTAR TODOS OS FUNCIONÁRIOS SEPARADAMENTE RESPECTIVAMENTE PELOS DEPARTAMENTOS DE FILMES E DEPARTAMENTO DE ROUPAS*/
SELECT idFuncionario, nome, departamento, COUNT(*)
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='ROUPAS')
GROUP BY DEPARTAMENTO,NOME;

/*EXERCÍCIO 2: O GESTOR DE MARKETING PEDIU A LISTA DE FUNCIONÁRIOS QUE TRABALHEM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO LAR. ELE NECESSITA ENVIAR UM EMAIL PARA AS COLABORADORAS DESSES DOIS SETORES*/

DESC FUNCIONARIOS;

SELECT NOME,SEXO FROM FUNCIONARIOS;

SELECT idFuncionario AS ID, nome AS COLABORADORA, email AS EMAIL,SEXO AS GENERO, DEPARTAMENTO, COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO LIKE '%F%' AND (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='LAR')
GROUP BY DEPARTAMENTO, NOME;

