/*VERIFICAR OS BANCOS DE DADOS*/
SHOW DATABASES;

/*UTILIZAR O BANCO FUNCIONÁRIOS*/
USE FUNCIONÁRIOS;

/*VERIFICAR AS TABELAS*/
SHOW TABLES;

/*DESCRIÇÃO DA TABELAS DE FUNCIONÁRIOS*/
DESC FUNCIONARIOS;

/*EXERCÍCIO 1: TRAGA OS FUNCIONÁRIOS QUE TRABALHAM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO DE ROUPAS*/

/*APRESENTAR TODOS OS NOMES DOS FUNCIONÁRIOS DOS DEPARTAMENTOS DE FILMES E DE ROUPAS POR ORDEM DE ID*/
SELECT idFuncionario, nome, departamento FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'FILMES' OR DEPARTAMENTO = 'ROUPAS';

/*APRESENTAR A QUANTIDADE DE FUNCIONÁRIOSDOS DEPARTAMENTOS DE FILMES E DE ROUPAS*/
SELECT idFuncionario, nome, departamento, COUNT(*)
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='ROUPAS')
GROUP BY DEPARTAMENTO;

/*APRESENTAR TODOS OS FUNCIONÁRIOS SEPARADAMENTE RESPECTIVAMENTE PELOS DEPARTAMENTOS DE FILMES E DEPARTAMENTO DE ROUPAS*/
SELECT idFuncionario, nome, departamento, COUNT(*)
FROM FUNCIONARIOS
WHERE (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='ROUPAS')
GROUP BY DEPARTAMENTO,NOME;

--CORREÇÃO PARA O EXERCÍCIO 1 APLICANDO PERFORMANCE
 
/*PODEMOS PRIMEIRO CHECAR QUANTOS FUNCIONÁRIOS TEM EM CADA DEPARTAMENTO ORDENANDO POR QUANTIDADE CRESCENTE ASSIM FAZEMOS UMA VERIFICAÇÃO EFCAZ*/
SELECT COUNT(*), DEPARTAMENTO
FROM FUNCIONÁRIOS
GROUP BY DEPARTAMENTO
ORDER BY 1;

/*APÓS ANALISÁRMOS AS QUANTIDADES PODEMOS APLICAR UMA QUERY QUE NÃO PREJUDIQUE A PERFORMANCEDO BANCO, DESTE MODO TEREMOS UM RESULTADO MAIS RÁPIDO SEM PREJUDICAR A USABILIDADE E EVITAR SOBRECARGA*/

--21 | FILMES  53 | ROUPAS

/*COMO TEMOS MAIOR NÚMERO DE FUNCIONÁRIOS NO DEPARTAMENTO DE ROUPAS PODEMOS TRAZER A QUERY OR VERIFICANDO PRIMEIRO ESSE DEPARTAMENTO FAZENDO COM QUE O SGBD NÃO VERIFIQUE A SEGUNDA CONDIÇÃO*/

SELECT idFuncionario AS ID, nome AS COLABORADOR, departamento FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'ROUPAS'
OR DEPARTAMENTO='FILMES';

/*SEPARANDO OS DEPARTAMENTOS, PODEMOS SEQUENCIAR POR ID OU POR SEQUÊNCIA ALFABÉTICA*/

SELECT idFuncionario AS ID, nome AS COLABORADOR, departamento FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'ROUPAS'
OR DEPARTAMENTO='FILMES'
GROUP BY DEPARTAMENTO, IDFUNCIONARIO;

SELECT idFuncionario AS ID, nome AS COLABORADOR, departamento FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'ROUPAS'
OR DEPARTAMENTO='FILMES'
GROUP BY DEPARTAMENTO, NOME;

/*LEVANDO EM CONSIDERAÇÃO QUE EM UM BANCO REAL NÃO PODEMOS FAZER QUERYS ASSIM EM HORÁRIOS DE PICOS DE UTILIZAÇÃO DO BANCO, POIS PREJUDICARIA MUITO A PERFORMANCE, O ESSENCIAL SERIA TER UMA SERVIDOR DE TESTES*/

--FIM DA CORREÇÃO

/*EXERCÍCIO 2: O GESTOR DE MARKETING PEDIU A LISTA DE FUNCIONÁRIOS QUE TRABALHEM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO LAR. ELE NECESSITA ENVIAR UM EMAIL PARA AS COLABORADORAS DESSES DOIS SETORES*/

DESC FUNCIONARIOS;

SELECT NOME,SEXO FROM FUNCIONARIOS;

/*APRESENTAR ID, NOME, EMAIL, GENERO E DAPARTAMENTO DE TODAS AS FUNCIONARIAS DOS RESPECTIVOS DEPARTAMENTOS FILMES E LAR*/
SELECT idFuncionario AS ID, nome AS COLABORADORA, email AS EMAIL,SEXO AS GENERO, DEPARTAMENTO, COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO LIKE '%F%' AND (DEPARTAMENTO='FILMES' OR DEPARTAMENTO='LAR')
GROUP BY DEPARTAMENTO, NOME;

--CORREÇÃO DO EXERCÍCIO 2

/*NA APLICAÇÕA DE PERFORMANCE PODEMOS PRIMEIRO VERIFICAR QUANTOS FUNCIONÁRIOS EXISTEM DE AMBOS OS SEXOS*/

SELECT COUNT(*), SEXO
FROM FUNCIONARIOS
GROUP BY SEXO;
-- 491 | FEMININO  489 | MASCULINO

/*AGORA PODEMOS VERIFICAR QUANTOS FUNCIONÁRIOS TEM EM CADA SETOR*/

SELECT COUNT(*), DEPARTAMENTO
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;
--52 | LAR  21 | FILMES

/*PODEMOS CONCLUIR QUE PARA UMA MELHOR PERFORMANCE TEREMOS QUE FAZER O BANCO TER O MENOR TRABALHO POSSÍVEL, POR ISSO TEREMOS QUE PRIMEIRO TRAZER A COMPARAÇÃO DE SEXO QUE CONTÉM O MAIOR NÚMERO DE LINHAS LOGO APÓS TEREMOS QUE TRABALHAR COM OR E FAZER A VERIFICAÇÃO DE FUNCIONÁRIS QUE TRABALHAM EM AMBOS SETORES FAZENDO A VERIFICAÇÃO PRIMEIRO NO SETOR DE MAIOR NÚMERO, TRAZENDO ASSIM UM RESULTADO MAIS EFICIENTE*/

SELECT idFuncionario AS ID, nome AS COLABORADORA, email AS EMAIL,SEXO AS GENERO, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE
(DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO')
OR
(DEPARTAMENTO= 'FILMES' AND SEXO = 'FEMININO');

--FIM DA CORREÇÃO

/*EXERCICIO 3: TRAZER OS FUNCIONARIOS DO SEXO MASCULINO OU OS FUNCIONARIOS QUE TRABALHEM NO SETOR JARDIM*/

/*APRESENTAR TODOS OS FUNCIONARIOS MARCULINOS E HOMENS E MULHERES QUE TRABALHEM NO DEPARTAMENTO JARDIM*/
SELECT idFuncionario AS ID, nome AS COLABORADOR, sexo AS GENERO,DEPARTAMENTO, COUNT(*)
FROM FUNCIONARIOS
WHERE (SEXO='MASCULINO' OR DEPARTAMENTO='JARDIM')
GROUP BY DEPARTAMENTO, NOME;

--CORREÇÃO EXERCÍCIO 3

/*COMO O SEXO MARCULINO CONTÉM UM NÚMERO MUITO MAIOR DE RESULTADOS COLOCAMOS ELE INICIALMENTE PARA A COMPARAÇÃO NO OR LOGO APÓS VEM O SETOR JARDIM*/

SELECT idFuncionario AS ID, nome AS COLABORADOR, sexo AS GENERO,DEPARTAMENTO, COUNT(*)
FROM FUNCIONARIOS
WHERE (SEXO='MASCULINO' OR DEPARTAMENTO='JARDIM');

--FIM DA CORREÇÃO
